name: Elixir CI

on:
  push:
    branches: [ main, update-ci ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-22.04

    # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/compatibility-and-deprecations.md
    strategy:
      matrix:
        include:

          # Elixir 1.12

          - elixir: 1.12.3
            otp_release: 24.3

          # Elixir 1.13

          - elixir: 1.13.4
            otp_release: 24.3

          - elixir: 1.13.4
            otp_release: 25.3

          # Elixir 1.14

          - elixir: 1.14.5
            otp_release: 24.3

          - elixir: 1.14.5
            otp_release: 25.3

          - elixir: 1.14.5
            otp_release: 26.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp_release }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ matrix.elixir }}-${{ matrix.otp_release }}-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Dialyzer
      run: mix dialyzer


  code_quality:
    name: Check or calculate code quality metrics
    runs-on: ubuntu-22.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.5'
        otp-version: '25.3'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: coveralls-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Send coveralls
      run: mix coveralls.github

